<?php
/** @var array $periods */
/** @var array $log */
?>
<div class="page-header"><div><h1>Finance Controls</h1><p>Control accounting periods and review irreversible financial actions.</p></div></div>
<div class="grid-2">
<section class="card"><h2>New financial period</h2><form method="post" action="/finance/controls/periods"><input type="hidden" name="_csrf" value="<?=htmlspecialchars(csrf_token())?>"><label>Name<input name="name" required maxlength="120" placeholder="Term 1 2026"></label><label>Starts<input type="date" name="starts_on" required></label><label>Ends<input type="date" name="ends_on" required></label><button type="submit">Create period</button></form></section>
<section class="card"><h2>Control rules</h2><ul><li>Open periods allow normal finance operations.</li><li>Locked periods prevent payment reversals and invoice voids.</li><li>Closed periods are final.</li><li>Paid invoices cannot be voided.</li></ul></section>
</div>
<section class="card"><h2>Financial periods</h2><table><thead><tr><th>Name</th><th>Dates</th><th>Status</th><th>Actions</th></tr></thead><tbody><?php foreach($periods as $p): ?><tr><td><?=htmlspecialchars((string)$p['name'])?></td><td><?=htmlspecialchars($p['starts_on'].' → '.$p['ends_on'])?></td><td><?=htmlspecialchars(strtoupper((string)$p['status']))?></td><td><?php if($p['status']==='open'): ?><form method="post" action="/finance/controls/periods/lock" style="display:inline"><input type="hidden" name="_csrf" value="<?=htmlspecialchars(csrf_token())?>"><input type="hidden" name="id" value="<?=$p['id']?>"><button type="submit">Lock</button></form><?php elseif($p['status']==='locked'): ?><form method="post" action="/finance/controls/periods/close" style="display:inline"><input type="hidden" name="_csrf" value="<?=htmlspecialchars(csrf_token())?>"><input type="hidden" name="id" value="<?=$p['id']?>"><button type="submit">Close</button></form><?php endif; ?></td></tr><?php endforeach; ?></tbody></table></section>
<section class="card"><h2>Control log</h2><table><thead><tr><th>Date</th><th>Action</th><th>Amount</th><th>Reason</th><th>Status</th></tr></thead><tbody><?php foreach($log as $row): ?><tr><td><?=htmlspecialchars((string)$row['created_at'])?></td><td><?=htmlspecialchars((string)$row['action_type'])?></td><td><?= $row['amount']===null?'—':'KES '.number_format((float)$row['amount'],2)?></td><td><?=htmlspecialchars((string)$row['reason'])?></td><td><?=htmlspecialchars((string)$row['status'])?></td></tr><?php endforeach; ?></tbody></table></section>
