<?php

declare(strict_types=1);
namespace Modules\Timetable\Repositories;
use App\Core\BaseRepository;
use App\Core\Tenant;
final class TimetableRepository extends BaseRepository
{
    protected function table(): string { return 'timetables'; }
    protected function tenantScoped(): bool { return true; }
    public function activePeriods(): array { return $this->db->select('SELECT * FROM timetable_periods WHERE school_id=:school_id AND is_active=1 ORDER BY period_no',['school_id'=>Tenant::id()]); }
    public function periods(): array { return $this->db->select('SELECT * FROM timetable_periods WHERE school_id=:school_id ORDER BY period_no',['school_id'=>Tenant::id()]); }
    public function academicYears(): array { return $this->db->select('SELECT * FROM academic_years WHERE school_id=:school_id ORDER BY starts_on DESC',['school_id'=>Tenant::id()]); }
    public function terms(int $academicYearId=0): array { $p=['school_id'=>Tenant::id()];$sql='SELECT * FROM terms WHERE school_id=:school_id';if($academicYearId>0){$sql.=' AND academic_year_id=:academic_year_id';$p['academic_year_id']=$academicYearId;}$sql.=' ORDER BY starts_on';return $this->db->select($sql,$p); }
    public function classes(): array { return $this->db->select('SELECT * FROM classes WHERE school_id=:school_id AND status="active" ORDER BY name',['school_id'=>Tenant::id()]); }
    public function streams(int $classId=0): array { $p=['school_id'=>Tenant::id()];$sql='SELECT * FROM streams WHERE school_id=:school_id AND status="active"';if($classId>0){$sql.=' AND class_id=:class_id';$p['class_id']=$classId;}$sql.=' ORDER BY name';return $this->db->select($sql,$p); }
    public function teachers(): array { return $this->db->select('SELECT id,employee_no,first_name,last_name FROM teachers WHERE school_id=:school_id AND status="active" ORDER BY first_name,last_name',['school_id'=>Tenant::id()]); }
    public function subjects(): array { return $this->db->select('SELECT id,name,code FROM subjects WHERE school_id=:school_id AND status="active" ORDER BY name',['school_id'=>Tenant::id()]); }
    public function canTeach(int $teacherId,int $subjectId,int $classId,?int $streamId=null): bool { $sql='SELECT COUNT(*) total FROM teacher_subjects WHERE school_id=:school_id AND teacher_id=:teacher_id AND subject_id=:subject_id AND class_id=:class_id AND (stream_id=:stream_id OR stream_id IS NULL)';$r=$this->db->selectOne($sql,['school_id'=>Tenant::id(),'teacher_id'=>$teacherId,'subject_id'=>$subjectId,'class_id'=>$classId,'stream_id'=>$streamId]);return(int)($r['total']??0)>0; }
    public function subjectBelongsToClass(int $classId,int $subjectId): bool { $r=$this->db->selectOne('SELECT COUNT(*) total FROM class_subjects WHERE school_id=:school_id AND class_id=:class_id AND subject_id=:subject_id',['school_id'=>Tenant::id(),'class_id'=>$classId,'subject_id'=>$subjectId]);return(int)($r['total']??0)>0; }
    public function findTimetable(int $id): ?array { return $this->db->selectOne('SELECT tt.*,ay.name academic_year_name,tr.name term_name FROM timetables tt JOIN academic_years ay ON ay.id=tt.academic_year_id JOIN terms tr ON tr.id=tt.term_id WHERE tt.id=:id AND tt.school_id=:school_id',['id'=>$id,'school_id'=>Tenant::id()]); }
    public function latest(?int $termId=null): ?array { $sql='SELECT tt.*,ay.name academic_year_name,tr.name term_name FROM timetables tt JOIN academic_years ay ON ay.id=tt.academic_year_id JOIN terms tr ON tr.id=tt.term_id WHERE tt.school_id=:school_id';$p=['school_id'=>Tenant::id()];if($termId!==null){$sql.=' AND tt.term_id=:term_id';$p['term_id']=$termId;}$sql.=' ORDER BY tt.id DESC LIMIT 1';return $this->db->selectOne($sql,$p); }
    public function grid(int $timetableId,?int $classId=null,?int $streamId=null): array { $sql='SELECT e.*,c.name class_name,str.name stream_name,CONCAT(t.first_name," ",t.last_name) teacher_name,sub.name subject_name,p.name period_name,p.starts_at,p.ends_at,p.period_no FROM timetable_entries e JOIN classes c ON c.id=e.class_id LEFT JOIN streams str ON str.id=e.stream_id JOIN teachers t ON t.id=e.teacher_id JOIN subjects sub ON sub.id=e.subject_id JOIN timetable_periods p ON p.id=e.period_id WHERE e.school_id=:school_id AND e.timetable_id=:timetable_id';$p=['school_id'=>Tenant::id(),'timetable_id'=>$timetableId];if($classId!==null){$sql.=' AND e.class_id=:class_id';$p['class_id']=$classId;}if($streamId!==null){$sql.=' AND e.stream_id=:stream_id';$p['stream_id']=$streamId;}$sql.=' ORDER BY e.class_id,e.stream_id,e.day_of_week,p.period_no';return $this->db->select($sql,$p); }
    public function conflicts(int $timetableId,int $classId,?int $streamId,int $teacherId,int $day,int $periodId,?int $ignoreId=null): array { $sql='SELECT e.id,e.class_id,e.stream_id,e.teacher_id,CONCAT(t.first_name," ",t.last_name) teacher_name,sub.name subject_name FROM timetable_entries e JOIN teachers t ON t.id=e.teacher_id JOIN subjects sub ON sub.id=e.subject_id WHERE e.school_id=:school_id AND e.timetable_id=:timetable_id AND e.day_of_week=:day AND e.period_id=:period_id';$p=['school_id'=>Tenant::id(),'timetable_id'=>$timetableId,'day'=>$day,'period_id'=>$periodId];if($ignoreId!==null){$sql.=' AND e.id<>:ignore_id';$p['ignore_id']=$ignoreId;}$sql.=' AND (e.teacher_id=:teacher_id OR (e.class_id=:class_id AND (e.stream_id=:stream_id OR e.stream_id IS NULL OR :stream_id_null IS NULL)))';$p+=['teacher_id'=>$teacherId,'class_id'=>$classId,'stream_id'=>$streamId,'stream_id_null'=>$streamId];return $this->db->select($sql,$p); }
    public function assignments(): array { return $this->db->select('SELECT ts.id,ts.teacher_id,ts.subject_id,ts.class_id,ts.stream_id,COALESCE(ts.periods_per_week,1) periods_per_week,ts.is_double,CONCAT(t.first_name," ",t.last_name) teacher_name,sub.name subject_name,c.name class_name,str.name stream_name FROM teacher_subjects ts JOIN teachers t ON t.id=ts.teacher_id AND t.status="active" JOIN subjects sub ON sub.id=ts.subject_id JOIN classes c ON c.id=ts.class_id LEFT JOIN streams str ON str.id=ts.stream_id WHERE ts.school_id=:school_id AND ts.class_id IS NOT NULL ORDER BY ts.periods_per_week DESC,ts.id',['school_id'=>Tenant::id()]); }
    public function clearEntries(int $timetableId): int { return $this->db->execute('DELETE FROM timetable_entries WHERE school_id=:school_id AND timetable_id=:timetable_id',['school_id'=>Tenant::id(),'timetable_id'=>$timetableId]); }
    public function createTimetable(int $academicYearId,int $termId,string $name): int { return (int)$this->db->insert('timetables',['school_id'=>Tenant::id(),'academic_year_id'=>$academicYearId,'term_id'=>$termId,'name'=>$name,'status'=>'draft']); }
    public function insertEntry(array $data): int { return (int)$this->db->insert('timetable_entries',array_merge(['school_id'=>Tenant::id()],$data)); }
    public function updateStatus(int $id,string $status): void { $this->db->execute('UPDATE timetables SET status=:status,published_at=CASE WHEN :status2="published" THEN CURRENT_TIMESTAMP ELSE published_at END WHERE id=:id AND school_id=:school_id',['status'=>$status,'status2'=>$status,'id'=>$id,'school_id'=>Tenant::id()]); }
    public function markGenerated(int $id): void { $this->db->execute('UPDATE timetables SET generated_at=CURRENT_TIMESTAMP,status="draft" WHERE id=:id AND school_id=:school_id',['id'=>$id,'school_id'=>Tenant::id()]); }
}
