-- EduSasa canonical 004: student records and supporting records.
CREATE TABLE IF NOT EXISTS students (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, school_id BIGINT UNSIGNED NOT NULL, admission_no VARCHAR(80) NOT NULL, first_name VARCHAR(100) NOT NULL, middle_name VARCHAR(100) NULL, last_name VARCHAR(100) NOT NULL, gender VARCHAR(30) NULL, date_of_birth DATE NULL, admission_date DATE NULL, current_class_id BIGINT UNSIGNED NULL, current_stream_id BIGINT UNSIGNED NULL, status ENUM('active','inactive','graduated','transferred','suspended') NOT NULL DEFAULT 'active', phone VARCHAR(40) NULL, email VARCHAR(190) NULL, address TEXT NULL, photo_path VARCHAR(255) NULL, deleted_at DATETIME NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, UNIQUE KEY uq_student_school_admission(school_id,admission_no), KEY idx_students_school_class(school_id,current_class_id), KEY idx_students_school_stream(school_id,current_stream_id), KEY idx_students_school_status(school_id,status)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS guardians (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, school_id BIGINT UNSIGNED NOT NULL, first_name VARCHAR(100) NOT NULL, last_name VARCHAR(100) NOT NULL, phone VARCHAR(40) NULL, email VARCHAR(190) NULL, relationship VARCHAR(80) NULL, address TEXT NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, KEY idx_guardians_school(school_id), KEY idx_guardians_phone(school_id,phone)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS student_guardians (student_id BIGINT UNSIGNED NOT NULL, guardian_id BIGINT UNSIGNED NOT NULL, relationship VARCHAR(80) NULL, is_primary TINYINT(1) NOT NULL DEFAULT 0, can_pickup TINYINT(1) NOT NULL DEFAULT 1, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY(student_id,guardian_id), KEY idx_student_guardians_guardian(guardian_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS student_medical (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, school_id BIGINT UNSIGNED NOT NULL, student_id BIGINT UNSIGNED NOT NULL, blood_group VARCHAR(20) NULL, allergies TEXT NULL, conditions TEXT NULL, medications TEXT NULL, emergency_notes TEXT NULL, doctor_name VARCHAR(160) NULL, doctor_phone VARCHAR(40) NULL, updated_by BIGINT UNSIGNED NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, UNIQUE KEY uq_student_medical(student_id), KEY idx_student_medical_school(school_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS student_discipline (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, school_id BIGINT UNSIGNED NOT NULL, student_id BIGINT UNSIGNED NOT NULL, incident_date DATE NOT NULL, category VARCHAR(100) NULL, description TEXT NOT NULL, action_taken TEXT NULL, status VARCHAR(50) NULL, recorded_by BIGINT UNSIGNED NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, KEY idx_student_discipline_student(school_id,student_id,incident_date)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS student_achievements (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, school_id BIGINT UNSIGNED NOT NULL, student_id BIGINT UNSIGNED NOT NULL, achievement_date DATE NULL, title VARCHAR(180) NOT NULL, description TEXT NULL, category VARCHAR(100) NULL, recorded_by BIGINT UNSIGNED NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, KEY idx_student_achievement_student(school_id,student_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS student_documents (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, school_id BIGINT UNSIGNED NOT NULL, student_id BIGINT UNSIGNED NOT NULL, document_type VARCHAR(100) NOT NULL, file_name VARCHAR(255) NOT NULL, file_path VARCHAR(500) NOT NULL, mime_type VARCHAR(120) NULL, file_size BIGINT UNSIGNED NULL, uploaded_by BIGINT UNSIGNED NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, KEY idx_student_documents_student(school_id,student_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS student_status_history (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, school_id BIGINT UNSIGNED NOT NULL, student_id BIGINT UNSIGNED NOT NULL, old_status VARCHAR(50) NULL, new_status VARCHAR(50) NOT NULL, reason VARCHAR(255) NULL, changed_by BIGINT UNSIGNED NULL, created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, KEY idx_student_status_history_student(school_id,student_id,created_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
