-- EduSasa canonical 007: finance foundation.
CREATE TABLE IF NOT EXISTS fee_categories (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, school_id BIGINT UNSIGNED NOT NULL, name VARCHAR(120) NOT NULL, code VARCHAR(60) NOT NULL, description TEXT NULL, active TINYINT(1) NOT NULL DEFAULT 1, created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, deleted_at TIMESTAMP NULL, UNIQUE KEY uq_fee_category_school_code(school_id,code), KEY idx_fee_category_school(school_id)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS fee_structures (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, school_id BIGINT UNSIGNED NOT NULL, name VARCHAR(150) NOT NULL, academic_year_id BIGINT UNSIGNED NULL, term_id BIGINT UNSIGNED NULL, target_class_id BIGINT UNSIGNED NULL, target_stream_id BIGINT UNSIGNED NULL, description TEXT NULL, status ENUM('draft','published','archived') NOT NULL DEFAULT 'draft', created_by BIGINT UNSIGNED NULL, created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, deleted_at TIMESTAMP NULL, KEY idx_fee_structure_school(school_id), KEY idx_fee_structure_period(academic_year_id,term_id), KEY idx_fee_structure_target(school_id,target_class_id,target_stream_id)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS fee_structure_items (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, fee_structure_id BIGINT UNSIGNED NOT NULL, category_id BIGINT UNSIGNED NOT NULL, name VARCHAR(150) NOT NULL, amount DECIMAL(14,2) NOT NULL DEFAULT 0, mandatory TINYINT(1) NOT NULL DEFAULT 1, created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, KEY idx_fee_item_structure(fee_structure_id), KEY idx_fee_item_category(category_id)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS student_fee_accounts (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, school_id BIGINT UNSIGNED NOT NULL, student_id BIGINT UNSIGNED NOT NULL, currency CHAR(3) NOT NULL DEFAULT 'KES', opening_balance DECIMAL(14,2) NOT NULL DEFAULT 0, created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, UNIQUE KEY uq_student_fee_account(school_id,student_id), KEY idx_fee_account_school(school_id)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS fee_invoices (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, school_id BIGINT UNSIGNED NOT NULL, student_id BIGINT UNSIGNED NOT NULL, invoice_no VARCHAR(80) NOT NULL, invoice_date DATE NOT NULL, due_date DATE NULL, status ENUM('draft','issued','partially_paid','paid','void','overdue') NOT NULL DEFAULT 'draft', subtotal DECIMAL(14,2) NOT NULL DEFAULT 0, discount DECIMAL(14,2) NOT NULL DEFAULT 0, total DECIMAL(14,2) NOT NULL DEFAULT 0, paid_amount DECIMAL(14,2) NOT NULL DEFAULT 0, balance DECIMAL(14,2) NOT NULL DEFAULT 0, notes TEXT NULL, created_by BIGINT UNSIGNED NULL, created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, deleted_at TIMESTAMP NULL, UNIQUE KEY uq_invoice_school_no(school_id,invoice_no), KEY idx_invoice_school_student(school_id,student_id), KEY idx_invoice_status(school_id,status)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS fee_invoice_items (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, invoice_id BIGINT UNSIGNED NOT NULL, category_id BIGINT UNSIGNED NULL, description VARCHAR(180) NOT NULL, quantity DECIMAL(10,2) NOT NULL DEFAULT 1, unit_amount DECIMAL(14,2) NOT NULL DEFAULT 0, amount DECIMAL(14,2) NOT NULL DEFAULT 0, created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP, KEY idx_invoice_item_invoice(invoice_id)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS fee_payments (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, school_id BIGINT UNSIGNED NOT NULL, student_id BIGINT UNSIGNED NOT NULL, receipt_no VARCHAR(80) NOT NULL, payment_date DATE NOT NULL, amount DECIMAL(14,2) NOT NULL, method VARCHAR(40) NOT NULL, reference VARCHAR(120) NULL, payer_name VARCHAR(160) NULL, notes TEXT NULL, status ENUM('pending','confirmed','reversed') NOT NULL DEFAULT 'confirmed', created_by BIGINT UNSIGNED NULL, created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, UNIQUE KEY uq_payment_school_receipt(school_id,receipt_no), KEY idx_payment_school_student(school_id,student_id), KEY idx_payment_reference(school_id,reference)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS fee_payment_allocations (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, payment_id BIGINT UNSIGNED NOT NULL, invoice_id BIGINT UNSIGNED NOT NULL, amount DECIMAL(14,2) NOT NULL, created_at TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE KEY uq_payment_invoice(payment_id,invoice_id), KEY idx_allocation_invoice(invoice_id)) ENGINE=InnoDB;
