<?php
declare(strict_types=1);
/** @var \App\Core\Router $router */
use Modules\Finance\Controllers\FinanceController;
use Modules\Finance\Controllers\FeeStructureController;
use Modules\Finance\Controllers\StudentLedgerController;
use Modules\Finance\Controllers\ReconciliationController;
use Modules\Finance\Controllers\PaymentChannelController;
use Modules\Finance\Controllers\PaymentProviderController;
use Modules\Finance\Controllers\PublicPaymentController;
use Modules\Finance\Controllers\ReceiptController;
use Modules\Finance\Controllers\FinanceAdjustmentController;
use Modules\Finance\Controllers\FinanceReportController;
use Modules\Finance\Controllers\FinanceControlController;
$router->group(['prefix'=>'/finance','middleware'=>['tenant','auth','permission:finance.view,finance.manage']],function($router){
$router->get('',[FinanceController::class,'index']);
$router->get('/reports',[FinanceReportController::class,'index'],['permission:finance.reports']);
$router->get('/reports/export',[FinanceReportController::class,'export'],['permission:finance.reports']);
$router->get('/controls',[FinanceControlController::class,'index'],['permission:finance.controls,finance.periods']);
$router->post('/controls/periods',[FinanceControlController::class,'createPeriod'],['csrf','permission:finance.periods']);
$router->post('/controls/periods/lock',[FinanceControlController::class,'lockPeriod'],['csrf','permission:finance.periods']);
$router->post('/controls/periods/close',[FinanceControlController::class,'closePeriod'],['csrf','permission:finance.periods']);
$router->post('/controls/payments/reverse',[FinanceControlController::class,'reversePayment'],['csrf','permission:finance.controls']);
$router->post('/controls/invoices/void',[FinanceControlController::class,'voidInvoice'],['csrf','permission:finance.controls']);
$router->get('/categories',[FinanceController::class,'categories'],['permission:finance.manage']);
$router->post('/categories',[FinanceController::class,'storeCategory'],['csrf','permission:finance.manage']);
$router->get('/invoices/create',[FinanceController::class,'createInvoice'],['permission:finance.manage']);
$router->post('/invoices',[FinanceController::class,'storeInvoice'],['csrf','permission:finance.manage']);
$router->get('/payments/create',[FinanceController::class,'createPayment'],['permission:finance.payments']);
$router->post('/payments',[FinanceController::class,'storePayment'],['csrf','permission:finance.payments']);
$router->post('/payments/mpesa/stk',[PaymentProviderController::class,'initiate'],['csrf','permission:finance.payments']);
$router->get('/students',[FinanceController::class,'students'],['permission:finance.view']);
$router->get('/students/{id}/ledger',[StudentLedgerController::class,'ledger'],['permission:finance.view']);
$router->get('/students/{id}/statement',[StudentLedgerController::class,'statement'],['permission:finance.view']);
$router->get('/fee-structures',[FeeStructureController::class,'index'],['permission:finance.view']);
$router->get('/fee-structures/create',[FeeStructureController::class,'create'],['permission:finance.manage']);
$router->post('/fee-structures',[FeeStructureController::class,'store'],['csrf','permission:finance.manage']);
$router->post('/fee-structures/publish',[FeeStructureController::class,'publish'],['csrf','permission:finance.manage']);
$router->post('/fee-structures/generate',[FeeStructureController::class,'generate'],['csrf','permission:finance.manage']);
$router->get('/reconciliation',[ReconciliationController::class,'index'],['permission:finance.reports']);
$router->post('/reconciliation/save',[ReconciliationController::class,'save'],['csrf','permission:finance.reports']);
$router->post('/reconciliation/confirm',[ReconciliationController::class,'confirm'],['csrf','permission:finance.reports']);
$router->get('/payment-methods',[PaymentChannelController::class,'index'],['permission:finance.manage']);
$router->post('/payment-methods/save',[PaymentChannelController::class,'save'],['csrf','permission:finance.manage']);
$router->post('/payment-methods/delete',[PaymentChannelController::class,'delete'],['csrf','permission:finance.manage']);
$router->get('/invoices/{id}/payment-link',[PublicPaymentController::class,'generateLink'],['permission:finance.payments']);
$router->get('/invoices/{id}/adjustments',[FinanceAdjustmentController::class,'show'],['permission:finance.adjustments']);
$router->post('/invoices/{id}/adjustments',[FinanceAdjustmentController::class,'adjust'],['csrf','permission:finance.adjustments']);
$router->get('/refunds',[FinanceAdjustmentController::class,'refunds'],['permission:finance.refunds']);
$router->post('/refunds/request',[FinanceAdjustmentController::class,'requestRefund'],['csrf','permission:finance.refunds']);
$router->post('/refunds/approve',[FinanceAdjustmentController::class,'approveRefund'],['csrf','permission:finance.refunds']);
$router->post('/refunds/process',[FinanceAdjustmentController::class,'processRefund'],['csrf','permission:finance.refunds']);
$router->get('/receipts/{id}',[ReceiptController::class,'show'],['permission:finance.view']);
});
$router->post('/api/v1/finance/mpesa/callback/{school_id}/{token}',[PaymentProviderController::class,'callback']);
$router->get('/pay/{token}',[PublicPaymentController::class,'show']);
$router->post('/pay/{token}',[PublicPaymentController::class,'initiate'],['csrf']);
$router->get('/pay/status/{id}',[PublicPaymentController::class,'status']);
$router->post('/pay/callback/mpesa',[PublicPaymentController::class,'mpesaCallback']);
$router->post('/pay/webhook/paystack',[PublicPaymentController::class,'paystackWebhook']);
$router->get('/pay/callback/paystack',[PublicPaymentController::class,'paystackReturn']);
$router->get('/pay/callback/pesapal',[PublicPaymentController::class,'pesapalCallback']);
$router->post('/pay/ipn/pesapal',[PublicPaymentController::class,'pesapalIpn']);
$router->get('/pay/ipn/pesapal',[PublicPaymentController::class,'pesapalIpn']);
