<?php $esc=fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8'); $data=$data??[]; $exam=$data['exam']??[]; $classes=$data['classes']??[]; $subjects=$data['subjects']??[]; $papers=$data['papers']??[]; ?>
<div class="page-header"><div><h1><?= $esc($exam['name']??'Examination') ?> — Papers</h1><p>Configure subjects, marks, weighting and paper schedules per class.</p></div><a href="/exams/<?= (int)($exam['id']??0) ?>" class="btn">Back to Examination</a></div>
<div class="card"><h2>Add Examination Paper</h2><form method="post" action="/exams/<?= (int)$exam['id'] ?>/papers"><input type="hidden" name="csrf_token" value="<?= $esc(csrf_token()) ?>"><div class="form-grid">
<label>Class *<select name="class_id" required><option value="">Select class</option><?php foreach($classes as $class): ?><option value="<?= (int)$class['id'] ?>"><?= $esc($class['name']) ?><?= $class['code']?' ('.$esc($class['code']).')':'' ?></option><?php endforeach; ?></select></label>
<label>Subject *<select name="subject_id" required><option value="">Select subject</option><?php foreach($subjects as $subject): ?><option value="<?= (int)$subject['subject_id'] ?>" data-class-id="<?= (int)$subject['class_id'] ?>"><?= $esc($subject['subject_name']) ?><?= $subject['subject_code']?' ('.$esc($subject['subject_code']).')':'' ?></option><?php endforeach; ?></select></label>
<label>Paper code *<input name="paper_code" required placeholder="P1"></label><label>Paper name *<input name="paper_name" required placeholder="Mathematics Paper 1"></label>
<label>Maximum marks *<input type="number" step="0.01" min="0.01" name="max_marks" value="100" required></label><label>Pass marks *<input type="number" step="0.01" min="0" name="pass_marks" value="40" required></label>
<label>Weight (%) *<input type="number" step="0.01" min="0.01" max="100" name="weight" value="100" required></label><label>Duration (minutes)<input type="number" min="1" max="1440" name="duration_minutes" placeholder="120"></label>
<label>Scheduled at<input type="datetime-local" name="scheduled_at"></label>
</div><label>Instructions<textarea name="instructions" rows="3" placeholder="Optional paper instructions."></textarea></label><button class="btn btn-primary" type="submit">Add Paper</button></form></div>
<div class="card"><h2>Configured Papers</h2><div class="table-wrap"><table><thead><tr><th>Class</th><th>Subject</th><th>Paper</th><th>Marks</th><th>Weight</th><th>Duration</th><th>Scheduled</th><th>Status</th><th>Actions</th></tr></thead><tbody>
<?php foreach($papers as $paper): ?><tr><td><?= $esc($paper['class_name']) ?></td><td><?= $esc($paper['subject_name']) ?></td><td><strong><?= $esc($paper['paper_code']) ?></strong><br><small><?= $esc($paper['paper_name']) ?></small></td><td><?= $esc($paper['pass_marks']) ?> / <?= $esc($paper['max_marks']) ?></td><td><?= $esc($paper['weight']) ?>%</td><td><?= $paper['duration_minutes']!==null?$esc($paper['duration_minutes']).' min':'—' ?></td><td><?= $paper['scheduled_at']?$esc($paper['scheduled_at']):'—' ?></td><td><?= $esc(ucfirst($paper['status'])) ?></td><td><div class="button-group"><?php $next=['draft'=>'ready','ready'=>'locked']; if(isset($next[$paper['status']])): ?><form method="post" action="/exams/<?= (int)$exam['id'] ?>/papers/status"><input type="hidden" name="csrf_token" value="<?= $esc(csrf_token()) ?>"><input type="hidden" name="paper_id" value="<?= (int)$paper['id'] ?>"><input type="hidden" name="status" value="<?= $next[$paper['status']] ?>"><button class="btn"><?= ucfirst($next[$paper['status']]) ?></button></form><?php endif; ?><?php if($paper['status']!=='locked'): ?><form method="post" action="/exams/<?= (int)$exam['id'] ?>/papers/delete" onsubmit="return confirm('Remove this paper?');"><input type="hidden" name="csrf_token" value="<?= $esc(csrf_token()) ?>"><input type="hidden" name="paper_id" value="<?= (int)$paper['id'] ?>"><button class="btn">Remove</button></form><?php endif; ?></div></td></tr><?php endforeach; ?>
<?php if(!$papers): ?><tr><td colspan="9">No examination papers configured yet.</td></tr><?php endif; ?></tbody></table></div></div>
<script>
(function(){const cls=document.querySelector('select[name="class_id"]');const sub=document.querySelector('select[name="subject_id"]');if(!cls||!sub)return;const filter=()=>{const id=cls.value;Array.from(sub.options).forEach(o=>{if(!o.value)return;o.hidden=id!==''&&o.dataset.classId!==id;});if(sub.selectedOptions[0]?.hidden)sub.value='';};cls.addEventListener('change',filter);filter();})();
</script>
