<?php
/** @var array $roles */ /** @var array $permissions */ /** @var array $users */ ?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Platform Access | EduSasa</title><style>
body{font-family:system-ui,sans-serif;margin:0;background:#f5f7fb;color:#172033}main{max-width:1250px;margin:auto;padding:28px}.card{background:#fff;border:1px solid #e5e7eb;border-radius:12px;padding:20px;margin-bottom:20px}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:11px;border-bottom:1px solid #eee;vertical-align:top}.muted{color:#667085}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:14px}label{display:block;font-weight:600;margin:8px 0 5px}input,textarea,select{width:100%;box-sizing:border-box;padding:9px;border:1px solid #d0d5dd;border-radius:8px}fieldset{border:1px solid #e5e7eb;border-radius:8px;padding:10px;margin-top:10px}fieldset label{font-weight:400}.btn{border:0;border-radius:8px;padding:10px 14px;cursor:pointer} .primary{background:#172033;color:white}</style></head><body><main>
<h1>Platform Access Control</h1><p class="muted">Database-driven roles and permissions for EduSasa platform staff.</p>
<div class="card"><h2>Roles</h2><table><thead><tr><th>Role</th><th>Type</th><th>Permissions</th></tr></thead><tbody><?php foreach($roles as $role): ?><tr><td><strong><?=htmlspecialchars($role['name'])?></strong><br><span class="muted"><?=htmlspecialchars($role['code'])?></span></td><td><?=!empty($role['is_system'])?'System':'Custom'?></td><td><?=htmlspecialchars(implode(', ',$role['permissions']??[]))?></td></tr><?php endforeach; ?></tbody></table></div>
<div class="card"><h2>Create custom role</h2><form method="post" action="/platform/access/roles"><div class="grid"><div><label>Code</label><input name="code" required pattern="[A-Za-z0-9_]+"></div><div><label>Name</label><input name="name" required></div><div><label>Description</label><input name="description"></div></div><fieldset><legend>Permissions</legend><?php foreach($permissions as $p): ?><label><input type="checkbox" name="permission_ids[]" value="<?=htmlspecialchars((string)$p['id'])?>"> <?=htmlspecialchars($p['name'])?> <span class="muted">(<?=htmlspecialchars($p['code'])?>)</span></label><?php endforeach; ?></fieldset><input type="hidden" name="is_active" value="1"><button class="btn primary" type="submit">Create role</button></form></div>
<div class="card"><h2>Platform users</h2><table><thead><tr><th>User</th><th>Status</th><th>Current roles</th></tr></thead><tbody><?php foreach($users as $user): ?><tr><td><?=htmlspecialchars($user['first_name'].' '.$user['last_name'])?><br><span class="muted"><?=htmlspecialchars($user['email'])?></span></td><td><?=htmlspecialchars($user['status'])?></td><td><?=htmlspecialchars($user['roles']??'None')?></td></tr><?php endforeach; ?></tbody></table></div>
</main></body></html>
