<?php
/** @var array $subscriptions */
/** @var array $plans */
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Subscriptions · EduSasa Platform</title><style>body{font-family:system-ui,sans-serif;margin:0;background:#f5f7fb;color:#172033}main{max-width:1250px;margin:auto;padding:32px}.card{background:#fff;border:1px solid #e6e9ef;border-radius:12px;padding:20px;margin-bottom:20px}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:12px;border-bottom:1px solid #eee}input,select,button{padding:9px;border:1px solid #d0d5dd;border-radius:7px;background:#fff}button{cursor:pointer}.toolbar{display:flex;gap:10px;flex-wrap:wrap}.muted{color:#667085}.status{font-weight:600}</style></head><body><main>
<h1>Subscriptions</h1><p class="muted">Manage school plans and subscription lifecycle.</p>
<div class="card"><form method="get" class="toolbar"><input name="search" placeholder="Search school or plan" value="<?= htmlspecialchars((string)($_GET['search']??'')) ?>"><select name="status"><option value="">All statuses</option><?php foreach(['trial','active','past_due','suspended','cancelled','expired'] as $status): ?><option value="<?= $status ?>" <?= ($_GET['status']??'')===$status?'selected':'' ?>><?= ucfirst(str_replace('_',' ',$status)) ?></option><?php endforeach; ?></select><button type="submit">Filter</button></form></div>
<div class="card"><table><thead><tr><th>School</th><th>Plan</th><th>Status</th><th>Billing</th><th>Change plan</th><th>Status action</th></tr></thead><tbody><?php foreach(($subscriptions??[]) as $s): ?><tr><td><?= htmlspecialchars((string)$s['school_name']) ?><br><span class="muted"><?= htmlspecialchars((string)$s['school_code']) ?></span></td><td><?= htmlspecialchars((string)$s['plan_name']) ?></td><td class="status"><?= htmlspecialchars((string)$s['status']) ?></td><td><?= htmlspecialchars((string)$s['billing_interval']) ?></td><td><form method="post" action="/platform/subscriptions/<?= (int)$s['school_id'] ?>/plan"><select name="plan"><?php foreach(($plans??[]) as $p): ?><option value="<?= htmlspecialchars((string)$p['code']) ?>" <?= $p['code']===$s['plan_code']?'selected':'' ?>><?= htmlspecialchars((string)$p['name']) ?></option><?php endforeach; ?></select><button type="submit">Apply</button></form></td><td><form method="post" action="/platform/subscriptions/<?= (int)$s['id'] ?>/status"><select name="status"><?php foreach(['trial','active','past_due','suspended','cancelled','expired'] as $status): ?><option value="<?= $status ?>" <?= $status===$s['status']?'selected':'' ?>><?= ucfirst(str_replace('_',' ',$status)) ?></option><?php endforeach; ?></select><button type="submit">Save</button></form></td></tr><?php endforeach; ?></tbody></table></div>
</main></body></html>
