<?php

declare(strict_types=1);
namespace App\Core;
final class Router {
 private array $routes=[]; private array $aliases=[]; private array $groupMiddleware=[]; private string $prefix='';
 public function registerMiddleware(string $alias,string $class):void{$this->aliases[$alias]=$class;}
 public function group(array $options,callable $callback):void{$p=$this->prefix;$m=$this->groupMiddleware;$this->prefix.=$options['prefix']??'';$this->groupMiddleware=array_merge($m,$options['middleware']??[]);$callback($this);$this->prefix=$p;$this->groupMiddleware=$m;}
 public function get(string $uri,mixed $handler,array $middleware=[]):void{$this->add('GET',$uri,$handler,$middleware);} public function post(string $uri,mixed $handler,array $middleware=[]):void{$this->add('POST',$uri,$handler,$middleware);} public function put(string $uri,mixed $handler,array $middleware=[]):void{$this->add('PUT',$uri,$handler,$middleware);} public function patch(string $uri,mixed $handler,array $middleware=[]):void{$this->add('PATCH',$uri,$handler,$middleware);} public function delete(string $uri,mixed $handler,array $middleware=[]):void{$this->add('DELETE',$uri,$handler,$middleware);}
 private function add(string $method,string $uri,mixed $handler,array $middleware):void{$uri=rtrim($this->prefix.$uri,'/')?:'/';$names=[];$pattern=preg_replace_callback('/\{([a-zA-Z_][a-zA-Z0-9_]*)\}/',function($m)use(&$names){$names[]=$m[1];return '([^/]+)';},$uri);$this->routes[]=['method'=>$method,'pattern'=>'#^'.$pattern.'$#','names'=>$names,'handler'=>$handler,'middleware'=>array_merge($this->groupMiddleware,$middleware)];}
 public function dispatch(Request $request):Response{foreach($this->routes as $route){if($route['method']!==$request->method()||!preg_match($route['pattern'],$request->uri(),$matches))continue;array_shift($matches);$params=$route['names']?array_combine($route['names'],$matches):[];return $this->pipeline($route['middleware'],$request,fn()=> $this->handler($route['handler'],$request,$params));}return Response::html('Not Found',404);}
 private function pipeline(array $stack,Request $request,\Closure $destination):Response{$next=$destination;foreach(array_reverse($stack) as $entry){[$alias,$param]=array_pad(explode(':',$entry,2),2,null);$next=function(Request $r)use($next,$alias,$param){$class=$this->aliases[$alias]??$alias;$mw=Container::getInstance()->make($class);return $param===null?$mw->handle($r,$next):$mw->handle($r,$next,$param);};}return $next($request);}
 private function handler(mixed $handler,Request $request,array $params):Response{if($handler instanceof \Closure)return $handler($request,$params);if(is_array($handler)){[$class,$method]=$handler;$c=Container::getInstance()->make($class);return $c->{$method}($request,$params);}if(is_string($handler)&&str_contains($handler,'@')){[$class,$method]=explode('@',$handler,2);$c=Container::getInstance()->make($class);return $c->{$method}($request,$params);}throw new \RuntimeException('Unsupported route handler.');}
}
